[package]
name = "table-importer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
dropkick = { path = "../dropkick" }
once_cell = "1.18.0"
scraper = "0.16.0"
