name: "Release Docker Image"

on:
  release:
    types: ["published"]

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  push-image:
    runs-on: "ubuntu-latest"
    permissions:
      packages: "write"
      contents: "read"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Login to ghcr.io"
        uses: "docker/login-action@v2"
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Extract metadata"
        id: "meta"
        uses: "docker/metadata-action@v4"
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: "Build and push image"
        uses: "docker/build-push-action@v3"
        with:
          context: "."
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
